# https://www.mkdocs.org/user-guide/configuration/
repo_name: sistemasoperativos-ciencias-unam.gitlab.io
repo_url: https://gitlab.com/SistemasOperativos-Ciencias-UNAM/sistemasoperativos-ciencias-unam.gitlab.io
edit_uri: -/tree/master/docs

site_name: Sistemas Operativos
site_description: Facultad de Ciencias - UNAM
copyright: CC-BY-SA-4.0
site_url: https://SistemasOperativos-Ciencias-UNAM.gitlab.io
site_dir: public
docs_dir: docs

# https://www.mkdocs.org/user-guide/choosing-your-theme/
theme:
  name: mkdocs
  # name: readthedocs
  locale: es
  collapse_navigation: true
  titles_only: true

markdown_extensions:
- toc:
    permalink: true
    separator: "-"
